// src/client/app/ui/configuration/components/machines/index.tsx
import { Button, Icon } from '@material-ui/core';
import { Add, ArrowDownward, ArrowUpward, Check, Edit, Warning } from '@material-ui/icons';
import * as React from 'react';
import { Link } from 'react-router-dom';

import { useDispatch, useSelector } from '../../../../hooks';
import { getMachines, sortMachines } from '../../../../operations/local/machines.operations.local';
import { invokeOperation } from '../../../../operations/operation-invoker';
import { actions } from '../../../../store/actions';
import { sortByKey } from '../../utils/sort.functions';

export const MachinesPage: React.FunctionComponent = () => {
  const dispatch = useDispatch();
  const machines = useSelector(state => state.machines);

  const move = (previousIndex: number, currentIndex: number) => {
    const orderedIds = [];
    machines.forEach((machine, index) => {
      if (index === previousIndex) {
        orderedIds[currentIndex] = machine.id;
      } else if (index === currentIndex) {
        orderedIds[previousIndex] = machine.id;
      } else {
        orderedIds[index] = machine.id;
      }
    });

    invokeOperation(dispatch, sortMachines(orderedIds)).subscribe((machines) => {
      dispatch(actions.machines.updateMachines(machines));
    });
  }

  const moveUp = (index: number) => {
    if (index <= 0) return;
    move(index, --index);
  };

  const moveDown = (index: number) => {
    if (index >= machines.length) return;
    move(index, ++index);
  }

  React.useEffect(() => {
    if (!machines) {
      invokeOperation(dispatch, getMachines()).subscribe(machines => {
        dispatch(actions.machines.updateMachines(machines));
      })
    }
  }, [machines]);

  if (!machines) return null;

  return (
    <table className="config-table users">
      <thead>
        <tr>
          <th className="hidden-mobile">Sort</th>
          <th>Name</th>
          <th>Machine Type</th>
          <th className="centered">Monitoring Enabled?</th>
          <th className="action">
            <Button component={Link} to="/configuration/machines/add">
              <Icon>
                <Add />
              </Icon>
              Add
            </Button>
          </th>
        </tr>
      </thead>
      <tbody>
        {machines.sort(sortByKey('sortIndex')).map((machine, index) => {
          return (
            <tr key={machine.id}>
              <td className="hidden-mobile">
                <Button disabled={!index} onClick={() => moveUp(index)}>
                  <ArrowUpward />
                </Button>
                <Button disabled={index === machines.length - 1} onClick={() => moveDown(index)}>
                  <ArrowDownward />
                </Button>
              </td>
              <td>{machine.name}</td>
              <td>{machine.type}</td>
              <td className="centered">{machine.disabled ? (<Icon><Warning /></Icon>) : (<Icon><Check /></Icon>)}</td>
              <td className="action">
                <Button component={Link} to={`/configuration/machines/edit/${machine.id}`}>
                  <Icon>
                    <Edit />
                  </Icon>
                  Edit
                </Button>
              </td>
            </tr>
          )
        })}
      </tbody>
    </table>
  )
};

// src/Overseer.Client/src/app/configuration/machines/machines.component.ts
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';
import { Component, OnInit } from '@angular/core';
import { Machine, MachineType } from '../../models/machine.model';
import { MachinesService } from '../../services/machines.service';
import { simpleMachineSort } from '../../shared/machine-sorts';

@Component({
  templateUrl: './machines.component.html',
  styleUrls: ['../configuration.scss'],
})
export class MachinesComponent implements OnInit {
  constructor(private machinesService: MachinesService) {}

  machines?: Machine[];

  getMachineTypeName(machineType: MachineType) {
    return MachineType[machineType];
  }

  ngOnInit() {
    this.machinesService.getMachines().subscribe((machines) => (this.machines = machines.sort(simpleMachineSort)));
  }

  moveUp(index: number) {
    if (index <= 0) {
      return;
    }

    this.move(index, --index);
  }

  moveDown(index: number) {
    if (!this.machines) return;
    if (index >= this.machines.length) return;

    this.move(index, ++index);
  }

  move(previousIndex: number, currentIndex: number) {
    if (!this.machines?.length) return;

    moveItemInArray(this.machines, previousIndex, currentIndex);
    this.machinesService.sortMachines(this.machines.map((m) => m.id)).subscribe();
  }

  drop(event: CdkDragDrop<string[]>) {
    this.move(event.previousIndex, event.currentIndex);
  }
}

<table *ngIf="machines" class="config-table drag-drop machines">
  <thead>
    <tr>
      <th class="sort-column" translate>sort</th>
      <th translate>name</th>
      <th translate class="hidden-mobile">machineType</th>
      <th class="centered" translate>monitoringEnabled</th>
      <th class="action">
        <a routerLink="/configuration/machines/add" mat-button> <mat-icon>add</mat-icon> {{ 'add' | i18next }} </a>
      </th>
    </tr>
  </thead>
  <tbody class="drag-boundary" cdkDropList (cdkDropListDropped)="drop($event)">
    <tr *ngFor="let machine of machines; let $index = index" cdkDrag cdkDragBoundary=".drag-boundary">
      <td class="sort-column">
        <button mat-button (click)="moveUp($index)" [disabled]="$index === 0">
          <mat-icon>arrow_drop_up</mat-icon>
        </button>
        <button mat-button (click)="moveDown($index)" [disabled]="$index === machines.length - 1">
          <mat-icon>arrow_drop_down</mat-icon>
        </button>
      </td>
      <th class="name">{{ machine.name }}</th>
      <td class="hidden-mobile">
        {{ getMachineTypeName(machine.machineType) }}
      </td>
      <td class="centered">
        <mat-icon *ngIf="machine.disabled">warning</mat-icon>
        <mat-icon *ngIf="!machine.disabled">check</mat-icon>
      </td>
      <td class="action">
        <a mat-button [routerLink]="['/configuration/machines/edit/', machine.id]">
          <mat-icon>edit</mat-icon>
          {{ 'edit' | i18next }}
        </a>
      </td>
    </tr>
    <tr *ngIf="!machines || !machines.length">
      <td colspan="4" class="empty" translate>noMachines</td>
    </tr>
  </tbody>
</table>
